version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "python/"
    schedule:
      interval: "weekly"

  - package-ecosystem: npm
    directory: "nodejs"
    schedule:
      interval: "weekly"

  - package-ecosystem: "maven"
    directory: "java"
    schedule:
      interval: "weekly"