name: "reusable-workflows-called"

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  reusable_workflows_called:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: "reusable_workflows_called"
      run: |
        echo ${{ inputs.url }}
        echo ${{ secrets.username }}
        echo ${{ secrets.password }}
      shell: bash