name: "reusable-workflows-called"

permissions:
  id-token: write
  contents: write
  checks: write
  actions: write
  packages: write
  
on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string

jobs:
  reusable_workflows_called:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: "reusable_workflows_called"
      run: |
        echo ${{ inputs.url }}
        echo ${{ secrets.username }}
        echo ${{ secrets.password }}
      shell: bash